// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using UnityEngine;

    public struct _0559c47b58cd7f3448fdc3a4cdd592d1_a583443744844345baf700de8d91b19e : IEntityCommand
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public Vector3 position;
            [FieldOffset(12)]
            public Vector3 direction;
        }

        public static unsafe _0559c47b58cd7f3448fdc3a4cdd592d1_a583443744844345baf700de8d91b19e FromInterop(System.IntPtr data, System.Int32 dataSize) 
        {
            if (dataSize != 24) {
                throw new System.Exception($"Given data size is not equal to the struct size. ({dataSize} != 24) " +
                    "for command with ID 7");
            }

            var orig = new _0559c47b58cd7f3448fdc3a4cdd592d1_a583443744844345baf700de8d91b19e();
            var comp = (Interop*)data;
            orig.position = comp->position;
            orig.direction = comp->direction;
            return orig;
        }

        public Vector3 position;
        public Vector3 direction;
        
        public Entity Entity { get; set; }
        public Coherence.ChannelID ChannelID { get; set; }
        public MessageTarget Routing { get; set; }
        public uint Sender { get; set; }
        public uint GetComponentType() => 7;
        
        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            return IEntityMapper.Error.None;
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() {
            return default;
        }

        public void NullEntityRefs(Entity entity) {
        }
        
        public _0559c47b58cd7f3448fdc3a4cdd592d1_a583443744844345baf700de8d91b19e(
        Entity entity,
        Vector3 position,
        Vector3 direction
)
        {
            Entity = entity;
            ChannelID = Coherence.ChannelID.Default;
            Routing = MessageTarget.All;
            Sender = 0;
            
            this.position = position; 
            this.direction = direction; 
        }
        
        public static void Serialize(_0559c47b58cd7f3448fdc3a4cdd592d1_a583443744844345baf700de8d91b19e commandData, IOutProtocolBitStream bitStream)
        {
            var converted_position = commandData.position.ToCoreVector3();
            bitStream.WriteVector3(converted_position, FloatMeta.NoCompression());
            var converted_direction = commandData.direction.ToCoreVector3();
            bitStream.WriteVector3(converted_direction, FloatMeta.NoCompression());
        }
        
        public static _0559c47b58cd7f3448fdc3a4cdd592d1_a583443744844345baf700de8d91b19e Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
        {
            var converted_position = bitStream.ReadVector3(FloatMeta.NoCompression());
            var dataposition = converted_position.ToUnityVector3();
            var converted_direction = bitStream.ReadVector3(FloatMeta.NoCompression());
            var datadirection = converted_direction.ToUnityVector3();
    
            return new _0559c47b58cd7f3448fdc3a4cdd592d1_a583443744844345baf700de8d91b19e()
            {
                Entity = entity,
                Routing = target,
                position = dataposition,
                direction = datadirection
            };   
        }
    }

}
