// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_38b8b48420f3e7b4d9f82407a0b85e92_25994a136b464c15b36fd92823931851 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_38b8b48420f3e7b4d9f82407a0b85e92_2a49917551f94402a16fb0d52f81c4ab : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_38b8b48420f3e7b4d9f82407a0b85e92_fa83490e8c594763ac337447cedcdd34 : ScaleBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(GenericScale);
        public override string CoherenceComponentName => "GenericScale";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherenceLocalScale); }
            set { coherenceSync.coherenceLocalScale = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((GenericScale)coherenceComponent).value;

            var simFrame = ((GenericScale)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (GenericScale)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new GenericScale();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_38b8b48420f3e7b4d9f82407a0b85e92_9fdec412ad0041b8bce3fe5380174997 : BoolBinding
    {   
        private global::HealthSystem CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::HealthSystem)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_38b8b48420f3e7b4d9f82407a0b85e92_8724297961366402026);
        public override string CoherenceComponentName => "_38b8b48420f3e7b4d9f82407a0b85e92_8724297961366402026";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.enabled); }
            set { CastedUnityComponent.enabled = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_38b8b48420f3e7b4d9f82407a0b85e92_8724297961366402026)coherenceComponent).enabled;

            var simFrame = ((_38b8b48420f3e7b4d9f82407a0b85e92_8724297961366402026)coherenceComponent).enabledSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_38b8b48420f3e7b4d9f82407a0b85e92_8724297961366402026)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.enabled = Value;
            }
            else
            {
                update.enabled = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.enabledSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _38b8b48420f3e7b4d9f82407a0b85e92_8724297961366402026();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_38b8b48420f3e7b4d9f82407a0b85e92_59d3a34830c84464a2bc2608451b493b : BoolBinding
    {   
        private global::PlayerShooting CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::PlayerShooting)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_38b8b48420f3e7b4d9f82407a0b85e92_1555132992935451924);
        public override string CoherenceComponentName => "_38b8b48420f3e7b4d9f82407a0b85e92_1555132992935451924";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.enabled); }
            set { CastedUnityComponent.enabled = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_38b8b48420f3e7b4d9f82407a0b85e92_1555132992935451924)coherenceComponent).enabled;

            var simFrame = ((_38b8b48420f3e7b4d9f82407a0b85e92_1555132992935451924)coherenceComponent).enabledSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_38b8b48420f3e7b4d9f82407a0b85e92_1555132992935451924)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.enabled = Value;
            }
            else
            {
                update.enabled = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.enabledSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _38b8b48420f3e7b4d9f82407a0b85e92_1555132992935451924();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_38b8b48420f3e7b4d9f82407a0b85e92_198234c48b5f476ab54815b95376d091 : BoolBinding
    {   
        private global::PlayerController CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::PlayerController)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_38b8b48420f3e7b4d9f82407a0b85e92_5221092905819149187);
        public override string CoherenceComponentName => "_38b8b48420f3e7b4d9f82407a0b85e92_5221092905819149187";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.enabled); }
            set { CastedUnityComponent.enabled = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_38b8b48420f3e7b4d9f82407a0b85e92_5221092905819149187)coherenceComponent).enabled;

            var simFrame = ((_38b8b48420f3e7b4d9f82407a0b85e92_5221092905819149187)coherenceComponent).enabledSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_38b8b48420f3e7b4d9f82407a0b85e92_5221092905819149187)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.enabled = Value;
            }
            else
            {
                update.enabled = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.enabledSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _38b8b48420f3e7b4d9f82407a0b85e92_5221092905819149187();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_38b8b48420f3e7b4d9f82407a0b85e92 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_38b8b48420f3e7b4d9f82407a0b85e92>();
        
        private global::HealthSystem _38b8b48420f3e7b4d9f82407a0b85e92_5800a6307a70485fbd722b11862f1ab5_CommandTarget;
        private global::PlayerShooting _38b8b48420f3e7b4d9f82407a0b85e92_f154a7d7a6634ed290ea283016f405df_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
            ["25994a136b464c15b36fd92823931851"] = new Binding_38b8b48420f3e7b4d9f82407a0b85e92_25994a136b464c15b36fd92823931851(),
            ["2a49917551f94402a16fb0d52f81c4ab"] = new Binding_38b8b48420f3e7b4d9f82407a0b85e92_2a49917551f94402a16fb0d52f81c4ab(),
            ["fa83490e8c594763ac337447cedcdd34"] = new Binding_38b8b48420f3e7b4d9f82407a0b85e92_fa83490e8c594763ac337447cedcdd34(),
            ["9fdec412ad0041b8bce3fe5380174997"] = new Binding_38b8b48420f3e7b4d9f82407a0b85e92_9fdec412ad0041b8bce3fe5380174997(),
            ["59d3a34830c84464a2bc2608451b493b"] = new Binding_38b8b48420f3e7b4d9f82407a0b85e92_59d3a34830c84464a2bc2608451b493b(),
            ["198234c48b5f476ab54815b95376d091"] = new Binding_38b8b48420f3e7b4d9f82407a0b85e92_198234c48b5f476ab54815b95376d091(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_38b8b48420f3e7b4d9f82407a0b85e92()
        {
            bakedCommandBindings.Add("5800a6307a70485fbd722b11862f1ab5", BakeCommandBinding__38b8b48420f3e7b4d9f82407a0b85e92_5800a6307a70485fbd722b11862f1ab5);
            bakedCommandBindings.Add("f154a7d7a6634ed290ea283016f405df", BakeCommandBinding__38b8b48420f3e7b4d9f82407a0b85e92_f154a7d7a6634ed290ea283016f405df);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
    
        private void BakeCommandBinding__38b8b48420f3e7b4d9f82407a0b85e92_5800a6307a70485fbd722b11862f1ab5(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _38b8b48420f3e7b4d9f82407a0b85e92_5800a6307a70485fbd722b11862f1ab5_CommandTarget = (global::HealthSystem)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("HealthSystem.TakeDamage", "(System.Single)", SendCommand__38b8b48420f3e7b4d9f82407a0b85e92_5800a6307a70485fbd722b11862f1ab5, ReceiveLocalCommand__38b8b48420f3e7b4d9f82407a0b85e92_5800a6307a70485fbd722b11862f1ab5, MessageTarget.All, _38b8b48420f3e7b4d9f82407a0b85e92_5800a6307a70485fbd722b11862f1ab5_CommandTarget, false);
        }
        
        private void SendCommand__38b8b48420f3e7b4d9f82407a0b85e92_5800a6307a70485fbd722b11862f1ab5(MessageTarget target, ChannelID channelID, object[] args)
        {
            var command = new _38b8b48420f3e7b4d9f82407a0b85e92_5800a6307a70485fbd722b11862f1ab5();
            
            int i = 0;
            command.damage = (System.Single)args[i++];
        
            client.SendCommand(command, target, entityId, channelID);
        }
        
        private void ReceiveLocalCommand__38b8b48420f3e7b4d9f82407a0b85e92_5800a6307a70485fbd722b11862f1ab5(MessageTarget target, ChannelID _, object[] args)
        {
            var command = new _38b8b48420f3e7b4d9f82407a0b85e92_5800a6307a70485fbd722b11862f1ab5();
            
            int i = 0;
            command.damage = (System.Single)args[i++];
            
            ReceiveCommand__38b8b48420f3e7b4d9f82407a0b85e92_5800a6307a70485fbd722b11862f1ab5(command);
        }

        private void ReceiveCommand__38b8b48420f3e7b4d9f82407a0b85e92_5800a6307a70485fbd722b11862f1ab5(_38b8b48420f3e7b4d9f82407a0b85e92_5800a6307a70485fbd722b11862f1ab5 command)
        {
            var target = _38b8b48420f3e7b4d9f82407a0b85e92_5800a6307a70485fbd722b11862f1ab5_CommandTarget;
            
            target.TakeDamage((System.Single)(command.damage));
        }
    
        private void BakeCommandBinding__38b8b48420f3e7b4d9f82407a0b85e92_f154a7d7a6634ed290ea283016f405df(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _38b8b48420f3e7b4d9f82407a0b85e92_f154a7d7a6634ed290ea283016f405df_CommandTarget = (global::PlayerShooting)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("PlayerShooting.ShootCommand", "(UnityEngine.Vector3UnityEngine.Vector3)", SendCommand__38b8b48420f3e7b4d9f82407a0b85e92_f154a7d7a6634ed290ea283016f405df, ReceiveLocalCommand__38b8b48420f3e7b4d9f82407a0b85e92_f154a7d7a6634ed290ea283016f405df, MessageTarget.All, _38b8b48420f3e7b4d9f82407a0b85e92_f154a7d7a6634ed290ea283016f405df_CommandTarget, false);
        }
        
        private void SendCommand__38b8b48420f3e7b4d9f82407a0b85e92_f154a7d7a6634ed290ea283016f405df(MessageTarget target, ChannelID channelID, object[] args)
        {
            var command = new _38b8b48420f3e7b4d9f82407a0b85e92_f154a7d7a6634ed290ea283016f405df();
            
            int i = 0;
            command.position = (UnityEngine.Vector3)args[i++];
            command.direction = (UnityEngine.Vector3)args[i++];
        
            client.SendCommand(command, target, entityId, channelID);
        }
        
        private void ReceiveLocalCommand__38b8b48420f3e7b4d9f82407a0b85e92_f154a7d7a6634ed290ea283016f405df(MessageTarget target, ChannelID _, object[] args)
        {
            var command = new _38b8b48420f3e7b4d9f82407a0b85e92_f154a7d7a6634ed290ea283016f405df();
            
            int i = 0;
            command.position = (UnityEngine.Vector3)args[i++];
            command.direction = (UnityEngine.Vector3)args[i++];
            
            ReceiveCommand__38b8b48420f3e7b4d9f82407a0b85e92_f154a7d7a6634ed290ea283016f405df(command);
        }

        private void ReceiveCommand__38b8b48420f3e7b4d9f82407a0b85e92_f154a7d7a6634ed290ea283016f405df(_38b8b48420f3e7b4d9f82407a0b85e92_f154a7d7a6634ed290ea283016f405df command)
        {
            var target = _38b8b48420f3e7b4d9f82407a0b85e92_f154a7d7a6634ed290ea283016f405df_CommandTarget;
            
            target.ShootCommand((UnityEngine.Vector3)(command.position),(UnityEngine.Vector3)(command.direction));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _38b8b48420f3e7b4d9f82407a0b85e92_5800a6307a70485fbd722b11862f1ab5 castedCommand:
                    ReceiveCommand__38b8b48420f3e7b4d9f82407a0b85e92_5800a6307a70485fbd722b11862f1ab5(castedCommand);
                    break;
                case _38b8b48420f3e7b4d9f82407a0b85e92_f154a7d7a6634ed290ea283016f405df castedCommand:
                    ReceiveCommand__38b8b48420f3e7b4d9f82407a0b85e92_f154a7d7a6634ed290ea283016f405df(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_38b8b48420f3e7b4d9f82407a0b85e92 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override List<ICoherenceComponentData> CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame)
        {
            if (!usesLodsAtRuntime)
            {
                return null;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                var components = new List<ICoherenceComponentData>()
                {
                    new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                };

                return components;
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
            
            return null;
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_38b8b48420f3e7b4d9f82407a0b85e92>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
