// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_0559c47b58cd7f3448fdc3a4cdd592d1_3b590fd3a7184491b426eac36e43db06 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_0559c47b58cd7f3448fdc3a4cdd592d1_62ea15f5e07149d0aeb72d5f6daed10e : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_0559c47b58cd7f3448fdc3a4cdd592d1_1e2aa432ea4741adb373fd3d3d6d233c : ScaleBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(GenericScale);
        public override string CoherenceComponentName => "GenericScale";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherenceLocalScale); }
            set { coherenceSync.coherenceLocalScale = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((GenericScale)coherenceComponent).value;

            var simFrame = ((GenericScale)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (GenericScale)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new GenericScale();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_0559c47b58cd7f3448fdc3a4cdd592d1 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_0559c47b58cd7f3448fdc3a4cdd592d1>();
        
        private global::PlayerShooting _0559c47b58cd7f3448fdc3a4cdd592d1_a583443744844345baf700de8d91b19e_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
            ["3b590fd3a7184491b426eac36e43db06"] = new Binding_0559c47b58cd7f3448fdc3a4cdd592d1_3b590fd3a7184491b426eac36e43db06(),
            ["62ea15f5e07149d0aeb72d5f6daed10e"] = new Binding_0559c47b58cd7f3448fdc3a4cdd592d1_62ea15f5e07149d0aeb72d5f6daed10e(),
            ["1e2aa432ea4741adb373fd3d3d6d233c"] = new Binding_0559c47b58cd7f3448fdc3a4cdd592d1_1e2aa432ea4741adb373fd3d3d6d233c(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_0559c47b58cd7f3448fdc3a4cdd592d1()
        {
            bakedCommandBindings.Add("a583443744844345baf700de8d91b19e", BakeCommandBinding__0559c47b58cd7f3448fdc3a4cdd592d1_a583443744844345baf700de8d91b19e);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
    
        private void BakeCommandBinding__0559c47b58cd7f3448fdc3a4cdd592d1_a583443744844345baf700de8d91b19e(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _0559c47b58cd7f3448fdc3a4cdd592d1_a583443744844345baf700de8d91b19e_CommandTarget = (global::PlayerShooting)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("PlayerShooting.ShootCommand", "(UnityEngine.Vector3UnityEngine.Vector3)", SendCommand__0559c47b58cd7f3448fdc3a4cdd592d1_a583443744844345baf700de8d91b19e, ReceiveLocalCommand__0559c47b58cd7f3448fdc3a4cdd592d1_a583443744844345baf700de8d91b19e, MessageTarget.All, _0559c47b58cd7f3448fdc3a4cdd592d1_a583443744844345baf700de8d91b19e_CommandTarget, false);
        }
        
        private void SendCommand__0559c47b58cd7f3448fdc3a4cdd592d1_a583443744844345baf700de8d91b19e(MessageTarget target, ChannelID channelID, object[] args)
        {
            var command = new _0559c47b58cd7f3448fdc3a4cdd592d1_a583443744844345baf700de8d91b19e();
            
            int i = 0;
            command.position = (UnityEngine.Vector3)args[i++];
            command.direction = (UnityEngine.Vector3)args[i++];
        
            client.SendCommand(command, target, entityId, channelID);
        }
        
        private void ReceiveLocalCommand__0559c47b58cd7f3448fdc3a4cdd592d1_a583443744844345baf700de8d91b19e(MessageTarget target, ChannelID _, object[] args)
        {
            var command = new _0559c47b58cd7f3448fdc3a4cdd592d1_a583443744844345baf700de8d91b19e();
            
            int i = 0;
            command.position = (UnityEngine.Vector3)args[i++];
            command.direction = (UnityEngine.Vector3)args[i++];
            
            ReceiveCommand__0559c47b58cd7f3448fdc3a4cdd592d1_a583443744844345baf700de8d91b19e(command);
        }

        private void ReceiveCommand__0559c47b58cd7f3448fdc3a4cdd592d1_a583443744844345baf700de8d91b19e(_0559c47b58cd7f3448fdc3a4cdd592d1_a583443744844345baf700de8d91b19e command)
        {
            var target = _0559c47b58cd7f3448fdc3a4cdd592d1_a583443744844345baf700de8d91b19e_CommandTarget;
            
            target.ShootCommand((UnityEngine.Vector3)(command.position),(UnityEngine.Vector3)(command.direction));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _0559c47b58cd7f3448fdc3a4cdd592d1_a583443744844345baf700de8d91b19e castedCommand:
                    ReceiveCommand__0559c47b58cd7f3448fdc3a4cdd592d1_a583443744844345baf700de8d91b19e(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_0559c47b58cd7f3448fdc3a4cdd592d1 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override List<ICoherenceComponentData> CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame)
        {
            if (!usesLodsAtRuntime)
            {
                return null;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                var components = new List<ICoherenceComponentData>()
                {
                    new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                };

                return components;
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
            
            return null;
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_0559c47b58cd7f3448fdc3a4cdd592d1>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
